name: Vercel Production Deployment
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
  pull_request:              # First condition - must be a pull request
    types:                   # You can specify which PR actions trigger it
      - opened              # When PR is first created
      - synchronize         # When new commits are pushed to PR
    branches:               
      - main               # Only for PRs targeting main branch
jobs:
  Deploy-Production:
    if: ${{ github.event_name == 'pull_request' && github.base_ref == 'main' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Clear npm cache
        run: npm cache clean --force --prefix frontend
      - name: Install dependencies
        run: npm install --prefix frontend
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
